config/routes.rb
Rails.application.routes.draw do
  root to: "departments#index"

  resources :departments, only: %i[index new create edit update destroy] do
    resources :approvers, shallow: true, only: %i[new edit update]
    resources :users, shallow: true do
      resources :timecards
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/approval_authority.rb
class ApprovalAuthority < ApplicationRecord
  belongs_to :user
  belongs_to :department
end

app/models/approver.rb
class Approver < ApplicationRecord
  belongs_to :user
  belongs_to :department
end

app/models/department.rb
class Department < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 10 }

  has_many :users, dependent: :destroy
  has_many :approval_authorities, dependent: :destroy
  has_many :approvers, through: :approval_authorities, source: :user
end

app/models/timecard.rb
class Timecard < ApplicationRecord
  validates :start_at, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :position, presence: true

  belongs_to :department
  has_many :timecards, dependent: :destroy
  has_many :approval_authorities, dependent: :destroy
  has_many :approvable_departments, through: :approval_authorities, source: :department

  enum position: %i{member manager}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/approvers_controller.rb
class ApproversController < ApplicationController
  def new
    @department = Department.find(params[:department_id])
    @approver = @department.approval_authorities.build
  end

  def edit
    @approver = ApprovalAuthorities.find(params[:id])
  end

  def update
    @approver = ApprovalAuthorities.find(params[:id])
    if @approver.update(approver_params)
      redirect_to departments_path
    else
      render :edit
    end
  end

  private

  def approver_params
    params.require(:approval_authority).permit(:user_id, :department_id)
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def index
    @departments = Department.all
    @user_counts = User.group(:department_id).count
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_url, notice: "作成しました"
    else
      render :new
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])
    if @department.update(department_params)
      redirect_to departments_path, notice: "更新しました"
    else
      render :edit
    end
  end

  def destroy
    @department = Department.find(params[:id])
    @department.destroy
    head :no_content
  end

  private

  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/timecards_controller.rb
class TimecardsController < ApplicationController
  before_action :set_user, only: [:index, :new, :create]
  def index
    @timecards = @user.timecards.all
  end

  def new
    @timecard = @user.timecards.build
    respond_to do |format|
			format.html{ redirect_to @timecard, notice: 'User was successfully created.' }
			format.js {}
		end
  end

  def create
    @timecard = @user.timecards.build(timecard_params)
    respond_to do |format|
      if @timecard.save
        format.html { redirect_to user_timecards_path(@timecard.user_id), notice: 'User was successfully created.' }
        # format.json { render :index, status: :created, location: @timecard }
        # format.js { @status = "success"}
      else
        format.html { render :new }
        # format.json { render json: @timecard.errors, status: :unprocessable_entity }
        # format.js { @status = "fail" }
      end
    end
  end

  private

  def timecard_params
    params.require(:timecard).permit(:user_id, :start_at, :end_at)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_department, only: [:index, :new, :create]
  def index
    @users = @department.users.where(active: true).page(params[:page]).per(2)
    @q = @users.search(params[:q])
    @users = @q.result
  end

  def new
    @user = @department.users.build
  end

  def create
    @user = @department.users.build(user_params)

    if @user.save
      redirect_to  department_users_url(@department)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to department_users_url(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :position, :active)
  end

  def set_department
    @department = Department.find(params[:department_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/departments/_error.html.haml
- if department.errors.any?
  #error_explanation
    %h2
      = department.errors.count
      件のエラーがあります。
    %ul
      - department.errors.full_messages.each do |msg|
        %li= msg

app/views/departments/_form.html.haml
= form_with model: department, local: true do |f|
  %div
    = f.label :name, "名前"
    = f.text_field :name, required: true
  %div= f.submit "作成"

app/views/departments/edit.html.haml
= render 'error', department: @department
%h1 部署更新
= render 'form', department: @department

app/views/departments/index.html.haml
%h1 部署一覧
%div= link_to '部署作成', new_department_path
%table
  %thead
    %tr
      %th 名前
      %th 作成日
      %th
      %th
  %tbody
    - @departments.each do |department|
      %tr
        %td= department.name
        %td= l department.created_at
        %td= link_to "#{@user_counts[department.id] || 0}人", department_users_path(department)
        %td= link_to "編集", edit_department_url(department), class: 'btn btn-success delete'
        %td= link_to '削除', department, method: :delete, remote: true, data: {confirm: "削除します"}, class: 'btn btn-danger delete'

app/views/departments/new.html.haml
= render 'error', department: @department
%h1 部署作成
= render 'form', department: @department

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Kintai
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/timecards/_form.html.haml
.modal-dialog
  .modal-content
    %h1 勤務時間入力

    = form_with model: [@user, @timecard], remote: true, local: true do |f|
      %div
        = f.time_select :start_at, required: true
      %div
        = f.time_select :end_at, required: true
      %div= f.submit "作成"
  

app/views/timecards/create.js.haml
- if @status == 'success'
  $("tbody").append("#{j(render("tr", timecard: @timecard))}");
- elsif @status == 'fail'
  alert('error!');
$("#timecard-modal").modal("hide");

app/views/timecards/index.html.haml
%h1 #{@user.name}のタイムカード
%div= link_to '作成', new_user_timecard_path, remote: true, class: "btn btn-lg btn-primary"
#timecard-modal.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
%table
  %thead
    %tr
      %th 開始時間
      %th 終了時間
  %tbody
    - @timecards.each do |timecard|
      %tr
        %td= timecard.start_at
        %td= timecard.end_at

app/views/timecards/new.js.haml
$("#timecard-modal").html("#{escape_javascript(render 'form')}")
$("#timecard-modal").modal("show")

app/views/users/_error.html.haml
- if user.errors.any?
  #error_explanation
    %h2
      = user.errors.count
      件のエラーがあります。
    %ul
      - user.errors.full_messages.each do |msg|
        %li= msg

app/views/users/_form.html.haml
= form_with model: [@department, @user], local: true do |f|
  %div
    = f.label :name, "名前"
    = f.text_field :name, required: true
  %div
    = f.label :email, "メール"
    = f.text_field :email, required: true
  %div
    = f.label :position, "役職"
    = f.select :position, [["平社員", "member"],["部長","manager"]]
  %div
    = f.label :active, "在職"
    = f.check_box :active

  %div= f.submit "作成"

app/views/users/edit.html.haml
= render 'error', user: @user
%h1 ユーザー編集

= form_with model:  @user, local: true do |f|
  %div
    = f.label :name, "名前"
    = f.text_field :name, required: true
  %div
    = f.label :email, "メール"
    = f.text_field :email, required: true
  %div
    = f.label :position, "役職"
    = f.select :position, [["平社員", "member"],["部長","manager"]]
  %div
    = f.label :active, "在職"
    = f.check_box :active

  %div= f.submit "作成"

app/views/users/index.html.haml
.row
  = search_form_for @q, url: '' do |f|
    .col-sm-4
      .form-group
        = f.search_field :name_cont, placeholder: 'ユーザー'
    .col-sm-2
      .form-group
        = f.submit '検索', name: nil

%h1 ユーザ-一覧
%div= link_to '作成', new_department_user_path
%table
  %thead
    %tr
      %th 名前
      %th メール
      %th 役職
      %th 在職
      %th
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= user.position
        %td= user.active
        %td= link_to '編集', edit_user_path(user)
        %td= link_to '勤怠入力', user_timecards_path(user)
= paginate @users

app/views/users/new.html.haml
= render 'error', user: @user, department: @department
%h1 ユーザー作成

= form_with model: [@department, @user], local: true do |f|
  %div
    = f.label :name, "名前"
    = f.text_field :name, required: true
  %div
    = f.label :email, "メール"
    = f.text_field :email, required: true
  %div
    = f.label :position, "役職"
    = f.select :position, [["平社員", "member"],["部長","manager"]]
  %div
    = f.label :active, "在職"
    = f.check_box :active

  %div= f.submit "作成"